version: 2.0
name: go-admin
settings:
  legacy:
    force: false
    interval: 0s
  schema:
    - name: go-admin
      path: .
      commands:
        run: true
      watcher:
        extensions:
        - go
        paths:
        -/
        ignored_paths:
          - .git
          - .realize
          - vendor